apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird.componentName" (dict "root" . "component" "management") }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.labels" (dict "root" . "component" "management") | nindent 4 }}
data:
  management.json: |-
    {{- include "netbird.managementConfig" . | nindent 4 }}
