{{- if .Values.backend.split.management.enabled }}
{{- if .Values.backend.split.management.serviceAccount.create }}
{{- $values := .Values.backend.split.management -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netbird.serviceAccountName" (dict "root" . "component" "management" "values" $values) }}
  namespace: {{ include "netbird.componentNamespace" (dict "root" . "component" "management") }}
  labels:
    {{- include "netbird.labels" (dict "root" . "component" "management") | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
