fullnameOverride: netbird

dashboard:
  config:
    api:
      httpEndpoint: https://netbird.example.com:443
      grpcEndpoint: https://netbird.example.com:443
    auth:
      authority: https://example.okta.com
      useAuth0: false
      supportedScopes: openid profile email groups
      redirectUri: /auth
      silentRedirectUri: /silent-auth
      tokenSource: idToken
  envFromSecret:
    AUTH_CLIENT_ID: netbird/idpClientID
    AUTH_AUDIENCE: netbird/idpNativeAppClientID
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: netbird-dashboard.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: netbird-dashboard-tls
        hosts:
          - netbird-dashboard.example.com

backend:
  split:
    management:
      container:
        cmd:
          args:
            - --disable-anonymous-metrics=false
            - --dns-domain=netbird.selfhosted
      envFromSecret:
        STUN_SERVER: netbird/stunServer
        TURN_SERVER: netbird/turnServer
        TURN_SERVER_USER: netbird/turnServerUser
        TURN_SERVER_PASSWORD: netbird/turnServerPassword
        IDP_CLIENT_ID: netbird/idpClientID
        OKTA_API_TOKEN: netbird/oktaApiToken
        IDP_NATIVEAPP_CLIENT_ID: netbird/idpNativeAppClientID
      config:
        stuns:
          - proto: udp
            uri: "{{ .STUN_SERVER }}"
            username: ""
            password: null
        turnConfig:
          turns:
            - proto: udp
              uri: "{{ .TURN_SERVER }}"
              username: "{{ .TURN_SERVER_USER }}"
              password: "{{ .TURN_SERVER_PASSWORD }}"
          credentialsTTL: 12h
          secret: secret
          timeBasedCredentials: false
        reverseProxy:
          trustedPeers:
            - 0.0.0.0/0
        embeddedIdp:
          enabled: false
        httpConfig:
          address: 0.0.0.0:33073
          authIssuer: https://example.okta.com
          authAudience: "{{ .IDP_CLIENT_ID }}"
          authKeysLocation: https://example.okta.com/oauth2/v1/keys
          authUserIDClaim: ""
          idpSignKeyRefreshEnabled: false
          oidcConfigEndpoint: https://example.okta.com/.well-known/openid-configuration
        idpManagerConfig:
          managerType: okta
          clientConfig:
            issuer: https://example.okta.com
            tokenEndpoint: https://example.okta.com/oauth2/v1/token
            clientID: "{{ .IDP_CLIENT_ID }}"
            clientSecret: ""
            grantType: client_credentials
          extraConfig:
            ApiToken: "{{ .OKTA_API_TOKEN }}"
        deviceAuthorizationFlow:
          provider: hosted
          providerConfig:
            audience: "{{ .IDP_NATIVEAPP_CLIENT_ID }}"
            authorizationEndpoint: ""
            domain: ""
            clientID: nativeclientid
            clientSecret: ""
            tokenEndpoint: https://example.okta.com/oauth2/v1/token
            deviceAuthEndpoint: https://example.okta.com/oauth2/v1/device/authorize
            scope: openid email groups
            useIDToken: true
            redirectURLs: null
        pkceAuthorizationFlow:
          providerConfig:
            audience: "{{ .IDP_CLIENT_ID }}"
            clientID: "{{ .IDP_CLIENT_ID }}"
            clientSecret: ""
            domain: ""
            authorizationEndpoint: https://example.okta.com/oauth2/v1/authorize
            tokenEndpoint: https://example.okta.com/oauth2/v1/token
            scope: openid profile email groups
            redirectURLs:
              - http://localhost:53000
            useIDToken: true
      ingress:
        http:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: netbird.example.com
              paths:
                - path: /api
                  pathType: ImplementationSpecific
          tls:
            - secretName: netbird-api-tls
              hosts:
                - netbird.example.com
        grpc:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/backend-protocol: GRPC
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          hosts:
            - host: netbird.example.com
              paths:
                - path: /management.ManagementService
                  pathType: ImplementationSpecific
          tls:
            - secretName: netbird-grpc-tls
              hosts:
                - netbird.example.com
      persistence:
        enabled: true
      log:
        file: console
        level: info

    signal:
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/backend-protocol: GRPC
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        hosts:
          - host: netbird.example.com
            paths:
              - path: /signalexchange.SignalExchange
                pathType: ImplementationSpecific
        tls:
          - secretName: netbird-signal-tls
            hosts:
              - netbird.example.com

    relay:
      resources:
        requests:
          cpu: 300m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 128Mi
      config:
        exposedAddress: rels://netbird.example.com:443/relay
        log:
          level: info
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: netbird.example.com
            paths:
              - path: /relay
                pathType: ImplementationSpecific
        tls:
          - secretName: netbird-relay-tls
            hosts:
              - netbird.example.com
