fullnameOverride: netbird

dashboard:
  config:
    api:
      httpEndpoint: https://netbird.example.com:443
      grpcEndpoint: https://netbird.example.com:443
    auth:
      authority: https://zitadel.example.com
      useAuth0: false
      supportedScopes: openid profile email offline_access api groups
      redirectUri: /nb-auth
      silentRedirectUri: /nb-silent-auth
  envFromSecret:
    AUTH_CLIENT_ID: netbird/idpClientID
    AUTH_CLIENT_SECRET: netbird/idpClientSecret

backend:
  split:
    management:
      envFromSecret:
        STUN_SERVER: netbird/stunServer
        TURN_SERVER: netbird/turnServer
        TURN_SERVER_USER: netbird/turnServerUser
        TURN_SERVER_PASSWORD: netbird/turnServerPassword
        IDP_SERVICE_USER: netbird/idpServiceUser
        IDP_SERVICE_USER_SECRET: netbird/idpServiceUserSecret
        IDP_PROJECT_ID: netbird/idpProjectID
        IDP_CLIENT_ID: netbird/idpClientID
      config:
        stuns:
          - proto: udp
            uri: "{{ .STUN_SERVER }}"
            username: ""
            password: ""
        turnConfig:
          timeBasedCredentials: false
          credentialsTTL: 12h
          secret: secret
          turns:
            - proto: udp
              uri: "{{ .TURN_SERVER }}"
              username: "{{ .TURN_SERVER_USER }}"
              password: "{{ .TURN_SERVER_PASSWORD }}"
        embeddedIdp:
          enabled: false
        httpConfig:
          authIssuer: https://zitadel.example.com
          authAudience: "{{ .IDP_CLIENT_ID }}"
          oidcConfigEndpoint: https://zitadel.example.com/.well-known/openid-configuration
          authKeysLocation: https://zitadel.example.com/oauth/v2/keys
          letsEncryptDomain: ""
          certFile: ""
          certKey: ""
          authUserIDClaim: ""
          idpSignKeyRefreshEnabled: true
          extraAuthAudience: "{{ .IDP_PROJECT_ID }}"
        idpManagerConfig:
          managerType: zitadel
          clientConfig:
            issuer: https://zitadel.example.com
            tokenEndpoint: https://zitadel.example.com/oauth/v2/token
            clientID: "{{ .IDP_SERVICE_USER }}"
            clientSecret: "{{ .IDP_SERVICE_USER_SECRET }}"
            grantType: client_credentials
          extraConfig:
            ManagementEndpoint: https://zitadel.example.com/management/v1
        deviceAuthorizationFlow:
          provider: hosted
          providerConfig:
            clientID: "{{ .IDP_CLIENT_ID }}"
            clientSecret: ""
            domain: zitadel.example.com
            audience: "{{ .IDP_CLIENT_ID }}"
            tokenEndpoint: https://zitadel.example.com/oauth/v2/token
            deviceAuthEndpoint: https://zitadel.example.com/oauth/v2/device_authorization
            authorizationEndpoint: ""
            scope: openid
            useIDToken: false
            redirectURLs: null
        pkceAuthorizationFlow:
          providerConfig:
            clientID: "{{ .IDP_CLIENT_ID }}"
            clientSecret: ""
            domain: ""
            audience: "{{ .IDP_CLIENT_ID }}"
            deviceAuthEndpoint: ""
            scope: openid profile email offline_access api groups zitadel:grants
            useIDToken: false
            redirectURLs:
              - http://localhost:53000/
              - http://localhost:54000/
            tokenEndpoint: https://zitadel.example.com/oauth/v2/token
            authorizationEndpoint: https://zitadel.example.com/oauth/v2/authorize
      persistence:
        enabled: true
        size: 5Gi

    relay:
      config:
        exposedAddress: rels://netbird.example.com:443/relay
        log:
          level: info

extraManifests:
  - apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: netbird-mgmt
    spec:
      gateways:
        - istio-gw/ext-gw
      hosts:
        - netbird.example.com
      http:
        - match:
            - uri:
                prefix: /api
          route:
            - destination:
                host: netbird-management
                port:
                  number: 80
        - match:
            - uri:
                prefix: /management.ManagementService
          route:
            - destination:
                host: netbird-management
                port:
                  number: 80
        - match:
            - uri:
                prefix: /relay
          route:
            - destination:
                host: netbird-relay
                port:
                  number: 33080
        - match:
            - uri:
                prefix: /signalexchange.SignalExchange
          route:
            - destination:
                host: netbird-signal
                port:
                  number: 80
  - apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: netbird-dashboard-mgmt-vs
      namespace: netbird
    spec:
      gateways:
        - istio-gw/ext-gw
      hosts:
        - netbird-dashboard.example.com
      http:
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: netbird-dashboard
                port:
                  number: 80
