fullnameOverride: netbird

dashboard:
  config:
    api:
      httpEndpoint: https://netbird.example.com:443
      grpcEndpoint: https://netbird.example.com:443
    auth:
      audience: netbird-banking
      authority: https://example.eu.auth0.com/
      useAuth0: true
      supportedScopes: openid profile email offline_access api email_verified
      tokenSource: accessToken
  envFromSecret:
    AUTH_CLIENT_ID: netbird/idpDashboardClientID
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: netbird-dashboard.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: netbird-dashboard-tls
        hosts:
          - netbird-dashboard.example.com

backend:
  split:
    management:
      container:
        cmd:
          args:
            - --disable-anonymous-metrics=false
            - --dns-domain=netbird.selfhosted
      envFromSecret:
        STUN_SERVER: netbird/stunServer
        TURN_SERVER: netbird/turnServer
        TURN_SERVER_USER: netbird/turnServerUser
        TURN_SERVER_PASSWORD: netbird/turnServerPassword
        IDP_CLIENT_ID: netbird/idpClientID
        IDP_CLIENT_SECRET: netbird/idpClientSecret
        IDP_INTERACTIVE_CLIENT_ID: netbird/idpInteractiveClientID
        IDP_DASHBOARD_CLIENT_ID: netbird/idpDashboardClientID
      config:
        stuns:
          - proto: udp
            uri: "{{ .STUN_SERVER }}"
            username: ""
            password: null
        turnConfig:
          turns:
            - proto: udp
              uri: "{{ .TURN_SERVER }}"
              username: "{{ .TURN_SERVER_USER }}"
              password: "{{ .TURN_SERVER_PASSWORD }}"
          credentialsTTL: 12h
          secret: secret
          timeBasedCredentials: false
        reverseProxy:
          trustedPeers:
            - 0.0.0.0/0
        embeddedIdp:
          enabled: false
        httpConfig:
          address: 0.0.0.0:33073
          authIssuer: https://example.eu.auth0.com/
          authAudience: netbird-banking
          authKeysLocation: https://example.eu.auth0.com/.well-known/jwks.json
          authUserIDClaim: ""
          certFile: ""
          certKey: ""
          idpSignKeyRefreshEnabled: false
          oidcConfigEndpoint: https://example.eu.auth0.com/.well-known/openid-configuration
        idpManagerConfig:
          managerType: auth0
          clientConfig:
            issuer: https://example.eu.auth0.com/
            tokenEndpoint: https://example.eu.auth0.com/oauth/token
            clientID: "{{ .IDP_CLIENT_ID }}"
            clientSecret: "{{ .IDP_CLIENT_SECRET }}"
            grantType: client_credentials
          extraConfig:
            Audience: https://example.eu.auth0.com/api/v2/
        deviceAuthorizationFlow:
          provider: hosted
          providerConfig:
            audience: netbird-banking
            authorizationEndpoint: ""
            domain: ""
            clientID: "{{ .IDP_INTERACTIVE_CLIENT_ID }}"
            clientSecret: ""
            tokenEndpoint: https://example.eu.auth0.com/oauth/token
            deviceAuthEndpoint: https://example.eu.auth0.com/oauth/device/code
            scope: openid
            useIDToken: false
            redirectURLs: null
        pkceAuthorizationFlow:
          providerConfig:
            audience: netbird-banking
            clientID: "{{ .IDP_DASHBOARD_CLIENT_ID }}"
            clientSecret: ""
            domain: ""
            authorizationEndpoint: https://example.eu.auth0.com/authorize
            tokenEndpoint: https://example.eu.auth0.com/oauth/token
            scope: openid groups profile email offline_access api email_verified groups
            redirectURLs:
              - http://localhost:53000
            useIDToken: false
      ingress:
        http:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: netbird.example.com
              paths:
                - path: /api
                  pathType: ImplementationSpecific
          tls:
            - secretName: netbird-api-tls
              hosts:
                - netbird.example.com
        grpc:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/backend-protocol: GRPC
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          hosts:
            - host: netbird.example.com
              paths:
                - path: /management.ManagementService
                  pathType: ImplementationSpecific
          tls:
            - secretName: netbird-grpc-tls
              hosts:
                - netbird.example.com
      persistence:
        enabled: true
      log:
        file: console
        level: error

    signal:
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/backend-protocol: GRPC
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        hosts:
          - host: netbird.example.com
            paths:
              - path: /signalexchange.SignalExchange
                pathType: ImplementationSpecific
        tls:
          - secretName: netbird-signal-tls
            hosts:
              - netbird.example.com

    relay:
      resources:
        requests:
          cpu: 300m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 256Mi
      config:
        exposedAddress: rels://netbird.example.com:443/relay
        log:
          level: info
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: netbird.example.com
            paths:
              - path: /relay
                pathType: ImplementationSpecific
        tls:
          - secretName: netbird-relay-tls
            hosts:
              - netbird.example.com
