{{- $values := .Values.backend.split.relay -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.componentName" (dict "root" . "component" "relay") }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.labels" (dict "root" . "component" "relay") | nindent 4 }}
  {{- with $values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $values.service.type }}
  ports:
    - name: http
      port: {{ $values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if $values.config.metrics.enabled }}
    - name: metrics
      port: {{ $values.config.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if $values.config.health.enabled }}
    - name: health
      port: {{ $values.config.health.port }}
      targetPort: health
      protocol: TCP
    {{- end }}
  selector:
    {{- include "netbird.selectorLabels" (dict "root" . "component" "relay") | nindent 4 }}
  {{- with $values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
