{{- if and (eq .Values.backend.mode "combined") .Values.backend.combined.serviceAccount.create }}
{{- $values := .Values.backend.combined -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netbird.serviceAccountName" (dict "root" . "component" "combined" "values" $values) }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.labels" (dict "root" . "component" "combined") | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
