{{- if .Values.management.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Values.management.configYaml | nindent 4 }}
{{- end -}}
