{{- if eq .Values.backend.mode "split" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird.componentName" (dict "root" . "component" "signal") }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.labels" (dict "root" . "component" "signal") | nindent 4 }}
data:
  config.yaml: |-
    {{- include "netbird.signalConfig" . | nindent 4 }}
{{- end }}
