{{- if and (eq .Values.backend.mode "combined") .Values.backend.combined.ingress.grpc.enabled }}
{{- $ingress := .Values.backend.combined.ingress.grpc -}}
{{- $serviceName := include "netbird.componentName" (dict "root" . "component" "combined") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netbird.componentName" (dict "root" . "component" "combined-grpc") }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.labels" (dict "root" . "component" "combined") | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with $ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $.Values.backend.combined.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
