fullnameOverride: netbird

dashboard:
  config:
    api:
      httpEndpoint: https://netbird.example.com:443
      grpcEndpoint: https://netbird.example.com:443
    auth:
      authority: https://idp.example.com/application/o/netbird/
      useAuth0: false
      supportedScopes: openid profile email offline_access api
      tokenSource: accessToken
  envFromSecret:
    AUTH_CLIENT_ID: netbird/idpClientID
    AUTH_AUDIENCE: netbird/idpClientID

backend:
  mode: split
  split:
    management:
      envFromSecret:
        NETBIRD_STORE_ENGINE_POSTGRES_DSN: netbird/postgresDSN
        STUN_SERVER: netbird/stunServer
        TURN_SERVER: netbird/turnServer
        TURN_SERVER_USER: netbird/turnServerUser
        TURN_SERVER_PASSWORD: netbird/turnServerPassword
        IDP_CLIENT_ID: netbird/idpClientID
        IDP_SERVICE_ACCOUNT_USER: netbird/idpServiceAccountUser
        IDP_SERVICE_ACCOUNT_PASSWORD: netbird/idpServiceAccountPassword
      config:
        stuns:
          - proto: udp
            uri: "{{ .STUN_SERVER }}"
            username: ""
            password: ""
        turnConfig:
          timeBasedCredentials: false
          credentialsTTL: 12h
          secret: secret
          turns:
            - proto: udp
              uri: "{{ .TURN_SERVER }}"
              username: "{{ .TURN_SERVER_USER }}"
              password: "{{ .TURN_SERVER_PASSWORD }}"
        embeddedIdp:
          enabled: false
        httpConfig:
          letsEncryptDomain: ""
          certFile: ""
          certKey: ""
          authAudience: "{{ .IDP_CLIENT_ID }}"
          authIssuer: https://idp.example.com/application/o/netbird/
          authUserIDClaim: ""
          authKeysLocation: https://idp.example.com/application/o/netbird/jwks/
          oidcConfigEndpoint: https://idp.example.com/application/o/netbird/.well-known/openid-configuration
          idpSignKeyRefreshEnabled: false
        idpManagerConfig:
          managerType: authentik
          clientConfig:
            issuer: https://idp.example.com/application/o/totmicro-traefik-netbird
            tokenEndpoint: https://idp.example.com/application/o/token/
            clientID: "{{ .IDP_CLIENT_ID }}"
            clientSecret: ""
            grantType: client_credentials
          extraConfig:
            Password: "{{ .IDP_SERVICE_ACCOUNT_PASSWORD }}"
            Username: "{{ .IDP_SERVICE_ACCOUNT_USER }}"
        deviceAuthorizationFlow:
          provider: hosted
          providerConfig:
            clientID: "{{ .IDP_CLIENT_ID }}"
            clientSecret: ""
            domain: idp.example.com
            audience: "{{ .IDP_CLIENT_ID }}"
            tokenEndpoint: https://idp.example.com/application/o/token/
            deviceAuthEndpoint: https://idp.example.com/application/o/device/
            authorizationEndpoint: ""
            scope: openid
            useIDToken: false
            redirectURLs: null
        pkceAuthorizationFlow:
          providerConfig:
            clientID: "{{ .IDP_CLIENT_ID }}"
            clientSecret: ""
            domain: ""
            audience: "{{ .IDP_CLIENT_ID }}"
            tokenEndpoint: https://idp.example.com/application/o/token/
            deviceAuthEndpoint: ""
            authorizationEndpoint: https://idp.example.com/application/o/authorize/
            scope: openid profile email offline_access api
            useIDToken: false
            redirectURLs:
              - http://localhost:53000
        storeConfig:
          engine: postgres
      persistence:
        enabled: false

    relay:
      config:
        exposedAddress: rels://netbird.example.com:443/relay
        log:
          level: info
